POST http://localhost:3001/api/blogs
content-type: application/json

{   
    "title": "reddit test",
    "author": "me",
    "url": "reddit.com/hoster",
    "likes": 10
}
###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "url": "reddit.com/hoster"
}