POST http://localhost:3001/api/blogs
content-type: application/json

{   
    "title": "now with user x2",
    "author": "me",
    "url": "reddit.com/hoster",
    "likes": 100,
    "userId": "61eb3ccde81764987929d502"
}
###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "url": "reddit.com/hoster"
}